# Generated by Django 4.2.4 on 2023-08-08 19:46

from django.db import migrations, models
import user_auth.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS auth;'),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, unique=True, validators=[user_auth.validators.validate_phone_number], verbose_name='Номер телефона')),
                ('invite_code', models.CharField(db_index=True, max_length=6, verbose_name='Личный инвайт-код пользователя')),
                ('activated_code', models.CharField(blank=True, null=True, max_length=6, verbose_name='Активированный код')),
                ('users_invited', models.TextField(blank=True, null=True, verbose_name='Клиенты, использовавшие код данного пользователя')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'auth"."user_profile',
            },
        ),
    ]
